# Generated by Django 4.1.1 on 2022-09-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-date',)},
        ),
    ]
